import Head from "next/head";
import React from "react";
import EasybankArticles from "../components/EasybankArticles";
import EasybankBody from "../components/EasybankBody";
import EasybankIntro from "../components/EasybankIntro";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>easybank - next generation digital banking</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className=' h-screen w-screen  font-publicsans'>
        <div className='absolute w-screen px-[14px]'>
          <img
            src='/image-mockups.png'
            alt=''
            className='mx-auto -translate-y-[60px]'
          />
        </div>
        <img src='/bg-intro-mobile.svg' alt='' className='w-screen sm:hidden' />
        <img
          src='/bg-intro-desktop.svg'
          alt=''
          className='hidden w-screen sm:inline-block'
        />
        <div className='-translate-y-[38px]'>
          <EasybankIntro />
          <EasybankBody />
          <EasybankArticles />
          <Footer />
        </div>
      </main>
    </React.Fragment>
  );
}
