import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>easybank - next generation digital banking</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className=' h-screen w-screen font-publicsans '>
        <div className='absolute w-screen px-[14px]'>
          <img
            src='/image-mockups.png'
            alt=''
            className='mx-auto -translate-y-[60px]'
          />
        </div>
        <img src='/bg-intro-mobile.svg' alt='' className='w-screen ' />
        <div className=' -translate-y-[38px]'>
          <div className='mx-6 flex flex-col items-center'>
            <h1 className='text-center  text-[40px] font-light leading-[47px] text-focussed'>
              Next generation digital banking
            </h1>
            <p className='mt-4 text-center text-[15px] font-light leading-[25px] text-unfocussed'>
              Take your financial life online. Your Easybnank account will be a
              one-stop-shop for spending, saving, budgeting, investing, and much
              more.
            </p>
            <button className='mt-8 mb-[88px] h-[44px] w-[163px] rounded-full bg-gradient-to-br from-[#33D35E] to-[#2AB6D9] font-publicsans text-sm font-bold leading-[28px] text-white'>
              Request Invite
            </button>
          </div>
          <div className='bg-[#F4F5F7] px-6 text-center'>
            <h2 className='pt-16 text-[32px] font-light leading-[38px] text-focussed'>
              Why choose Easybank?
            </h2>
            <p className='mt-3.5 text-[15px] font-light leading-[25px] text-unfocussed'>
              We leverage Open Banking to turn your bank account into your
              financial hub. Control your finances like never before.
            </p>
            <img src='/icon-online.svg' alt='' className='mx-auto mt-14' />
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
